# Sync StoryTree Workflows
#
# This workflow automatically syncs GitHub workflows from the .StoryTree submodule
# to the project's .github/ directory.
#
# Triggers:
# 1. repository_dispatch from StoryTree's notify-dependents workflow (recommended)
# 2. Push to main that modifies the submodule (fallback)
# 3. Manual workflow_dispatch
#
# GitHub doesn't follow symlinks for workflows, so they must be copied.
# This automation ensures workflows stay in sync without manual intervention.

name: Sync StoryTree Workflows

on:
  repository_dispatch:
    types: [storytree-updated]
  push:
    paths:
      - '.gitmodules'
      - '.StoryTree'
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: sync-storytree
      cancel-in-progress: true
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodule to latest
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "Triggered by StoryTree update: ${{ github.event.client_payload.ref }}"
          cd .StoryTree
          git fetch origin main
          git checkout origin/main
          cd ..
          echo "Submodule updated to: $(cd .StoryTree && git rev-parse HEAD)"

      - name: Sync workflows from StoryTree
        run: |
          # Copy workflows and actions from submodule
          cp -r .StoryTree/github/workflows/* .github/workflows/
          cp -r .StoryTree/github/actions/* .github/actions/ 2>/dev/null || true

      - name: Check for changes
        id: changes
        run: |
          # Check both workflow files and submodule pointer
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git diff --cached --name-only
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: sync workflows from StoryTree submodule"
          git push
